### ISSUE TITLE
gjp page not being

### ISSUE THREAD

**Issue by sSolsta** [gd-programming/gd.docs#56]
![image](https://user-images.githubusercontent.com/52147022/118352649-d7d19500-b5a5-11eb-9be8-e2ec529e206b.png)
page that doesn't exist: [https://docs.gdprogra.me/#/topics/encryption/gjp](url)
page that links to it: [https://docs.gdprogra.me/#/endpoints/acceptGJFriendRequest20](url)

**Comment by IamAcand** [comment]
i can access it just fine

**Comment by nekitdev** [comment]
Closing this as related issues are being fixed on the `docs` branch.
