### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by kryllyxofficial01** [gd-programming/gd.docs#90]
It says I cannot access boomlings.com.

![Capture](https://user-images.githubusercontent.com/97801783/188284740-3b2e911f-2805-4ad3-84a3-81801f550c54.PNG)

**Comment by Alphatism** [comment]
Make sure there is no user agent and make sure you have the "www." as that is required now

**Comment by kryllyxofficial01** [comment]
What's a user agent?

**Comment by kryllyxofficial01** [comment]
I tried adding "www" to the link, but it still says access denied.

**Comment by naoei** [comment]
You're not going to get anywhere by visiting the server, as that can only send a GET request. Install a REST client such as [Insomnia](https://insomnia.rest) and try it from there.

I also recommend learning about how web requests work and how to communicate with robtop's server (as it's actually untraditional) in the [request page](https://docs.gdprogra.me/#/endpoints/request) within GD.Docs.

**Comment by nekitdev** [comment]
Closing this issue as "not planned".

**Comment by kryllyxofficial01** [comment]
The problem is that when I do the code shown, it returns the html code for the page, which shows the access denied page.

**Comment by naoei** [comment]
Please re-read what I've said.

**Comment by matcool** [comment]
That link is a bit outdated, heres a newer guide on the requirements for making requests to gd's servers
https://github.com/gd-programming/gd.docs-v2/blob/main/docs/endpoints/generic.md
