### ISSUE TITLE
Diamond Count

### ISSUE THREAD

**Issue by kryllyxofficial01** [gd-programming/gd.docs#91]
I was looking at the server response for a user, and I noticed that there doesn't seem to be a diamond count anywhere. Does the server return that somewhere else?

**Comment by Cvolton** [comment]
user search doesn't actually return diamond count (note that the client always shows 0), profiles do though

**Comment by kryllyxofficial01** [comment]
Is there anyway to get the diamond count?

**Comment by kryllyxofficial01** [comment]
The reason I used getGJUsers is because I'm making a Discord bot. But I think since I get the account ID from geGJUsers, I can then call getGJUserInfo, and get all of the stats. Thanks.
