### ISSUE TITLE
I cant send requests to GD servers

### ISSUE THREAD

**Issue by HGStyle** [gd-programming/gd.docs#98]
Hi, I tried a code to upload an account comment on my account with a Python programm.
I did the following : 
```python
import requests
data = {
    "accountID": 14819640,
    "gjp": "my encrypted gjp here",
    "comment": "VGhpcyBjb21tZW50IHdhcyBzZW5kIHdpdGggYSBQeXRob24gcHJvZ3JhbW0gYnkgSEdTdHlsZSAh",
    "secret": "Wmfd2893gb7"
}
r = requests.post('http://boomlings.com/database/uploadGJAccComment20.php', data=data)
print(r.text)
```
Note that the comment is URL-Safe Base64 Encoded.
The account ID is my Geometry Dash account ID (I fond it on https://gdbrowser.com/u/HGStyle)
But here is the response on an online HTML code viewer : https://codebeautify.org/htmlviewer/y2245a045

CloudFlare is blocking my request. But why ?
I allready tried using the package `cloudscraper` because this package bypasses CloudFlare verification, but it does not work.
I tried with a proxy too, and with custom User-Agent in headers, but it still does not work.
Can someone help me please ?
Thanks in advance !

**Comment by HGStyle** [comment]
Here is the content of the file i used to encode things like GJP or comment : 
```python
import base64
import hashlib
import itertools
import random
import string

def base64_encode(string: str) -> str:
    """Base64 Encode a string. Use the basic `base64` Python module to do that."""
    return base64.urlsafe_b64encode(string.encode()).decode()


def base64_decode(string: str) -> str:
    """Base64 Decode a string. Use the basic `base64` Python module to do that."""
    return base64.urlsafe_b64decode(string.encode()).decode()

def generate_chk(values: [int, str] = [], key: str = "", salt: str = "") -> str:
    values.append(salt)
    string = ("").join(map(str, values))
    hashed = hashlib.sha1(string.encode()).hexdigest()
    xored = xor_cipher(hashed, key)
    final = base64.urlsafe_b64encode(xored.encode()).decode()
    return final

def xor_cipher(string: str, key: str) -> str:
    return ("").join(chr(ord(x) ^ ord(y)) for x, y in zip(string, itertools.cycle(key)))

def generate_rs(n: int) -> str:
    return ("").join(random.choices(string.ascii_letters + string.digits, k=n))

def generate_uuid(parts: [int] = (8, 4, 4, 4, 10)) -> str:
    return ("-").join(map(generate_rs, parts))

def generate_udid(start: int = 100_000, end: int = 100_000_000) -> str:
    return "S" + str(random.randint(start, end))

def generate_gjp(password: str):
	gjp = xor_cipher(password, "37526")
	gjp = base64_encode(gjp)
	return gjp

**Comment by SMJSGaming** [comment]
You have to unset the user agent, that's all you need to do to bypass Cloudflare. Next time please refer to the support channel of GD Programming for help with your code.

**Comment by HGStyle** [comment]
> You have to unset the user agent, that's all you need to do to bypass Cloudflare. Next time please refer to the support channel of the GD Programming server for help with your code.

I asked on the server and it works now, but I forgot to close the issue.
